# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Tridondon-Blog
tagline:          'A Jekyll theme'
description:      '三角東東是……等專業人士共同組成，讓美感與設計蔓延至您生活的每一個角落。'
url:              http://hyde.getpoole.com
baseurl:          '/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

sass:
  sass_dir: assets/sass
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      image: /assets/hero/hero-img.jpg
