
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none


# Setup
title:            '三角東東'
tagline:          'A Jekyll theme'
description:      '三角東東是……等專業人士共同組成，讓美感與設計蔓延至您生活的每一個角落。'


# Need GitHub Page -> '/2020-11_tri_blog'
# baseurl:          '2020-11_tri_blog'

# Need _site output -> '.'
# baseurl:          ''

# baseurl:          '/'

# url:              'anderice.github.io'




author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate: 6
paginate_path: "/page:num/"



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

sass:
  sass_dir: _sass
  style: compressed


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      categories: undefined
      tag: undefined
      image: ./assets/imgs/placehold.png
